### PR TITLE
[READY] Client side sig help offsets

### PR DESCRIPTION
**Pull request by bstaletic**
# PR Prelude

Thank you for working on YCM! :)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [x] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [x] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

[Please explain **in detail** why the changes in this PR are needed.]

This is supposed to accompany puremourning/ycmd-1#20. No tests because they already didn't work.

[cont]: https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md
[code]: https://github.com/Valloric/YouCompleteMe/blob/master/CODE_OF_CONDUCT.md

---
This change is [Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/4)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
> No tests because they already didn't work.

Oh poop. Now what did i break...

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/4#-:-Lqumf9iBBV1VPwuCmBj:b309zew)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic)

___
*[python/ycm/signature_help.py, line 73 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/4#-LqumlLGD_odFlKNczSH:-LqumlLGD_odFlKNczSI:b-dy261y) ([raw file](https://github.com/puremourning/youcompleteme/blob/3976cafea5c037bcb16a4e3b7fd1def014b7de99/python/ycm/signature_help.py#L73)):*
> ```Python
>     for param_index, parameter in enumerate( parameters ):
>       param_label = parameter[ 'label' ]
>       begin = int( param_label[ 0 ] )
> ```

why is the cast needed ? is it because json numbers aren't ints ?
___
*[python/ycm/signature_help.py, line 77 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/4#-LqumsAkDzgiKX1Yi0Hy:-LqumsAkDzgiKX1Yi0Hz:bjeh2fh) ([raw file](https://github.com/puremourning/youcompleteme/blob/3976cafea5c037bcb16a4e3b7fd1def014b7de99/python/ycm/signature_help.py#L77)):*
> ```Python
>       if param_index == active_parameter:
>         props.append( {
>           'col': begin + 1, # 1-based
> ```

yeah, this is a byte index here (in vim-land), so i think we have a unicode bug. I think ycmd should return byte offsets

**Review by bstaletic — COMMENTED** [review]
I had an elaborate analysis of what's going on, but I couldn't figure it out. You can probably dig up one of my old comments in some other review. Yes, I'm being really vague, but I can't find that comment anywhere.

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/4#-:-LqupRPF30ZycrrMHNMJ:bbe95sd)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[python/ycm/signature_help.py, line 73 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/4#-LqumlLGD_odFlKNczSH:-LqupiwBBf7sOdZxfds1:bwvmg6o) ([raw file](https://github.com/puremourning/youcompleteme/blob/3976cafea5c037bcb16a4e3b7fd1def014b7de99/python/ycm/signature_help.py#L73)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

why is the cast needed ? is it because json numbers aren't ints ?
</blockquote></details>

It's because of https://github.com/vim/vim/issues/5043

If we pass a python dictionary to vim and back to python, vim turns all `int`s into strings. That's why you also have `activeSignature` casted to `int` a few lines above.
___
*[python/ycm/signature_help.py, line 77 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/4#-LqumsAkDzgiKX1Yi0Hy:-Lquq3C77COOCW_N9R77:b-8522zq) ([raw file](https://github.com/puremourning/youcompleteme/blob/3976cafea5c037bcb16a4e3b7fd1def014b7de99/python/ycm/signature_help.py#L77)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

yeah, this is a byte index here (in vim-land), so i think we have a unicode bug. I think ycmd should return byte offsets
</blockquote></details>

Again, does that mean `CodepointOffsetToByteOffset` and we're done?

**Review by puremourning — COMMENTED** [review]
I fixed the test sorta in my branch. the vim tests are still failing, though, which i can repro locally.

There is something really wonky that sometimes happens where there's a random Unpickling errorr coming from somewhere. i honestly have no clue what's causing that.... investigating

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/4#-:-LquxUGx0J9soepAcDen:b-9zit6i)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/4)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic and @puremourning)

___
*[python/ycm/signature_help.py, line 77 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/4#-LqumsAkDzgiKX1Yi0Hy:-Lquz7tV9zOt-heorDDU:b-g9sh8) ([raw file](https://github.com/puremourning/youcompleteme/blob/3976cafea5c037bcb16a4e3b7fd1def014b7de99/python/ycm/signature_help.py#L77)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Again, does that mean `CodepointOffsetToByteOffset` and we're done?
</blockquote></details>

if we change ycmd to send byte offsets, then no change is needed here; the text properties expect byte offsets.

**Review by bstaletic — COMMENTED** [review]
Rebased onto the tip of your branch.

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/4#-:-Lqv00Hx0JPjHqgJrTbc:b-hu9owd)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[python/ycm/signature_help.py, line 77 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/4#-LqumsAkDzgiKX1Yi0Hy:-Lqv-n4_EpOAGuhM2Vge:b-896fix) ([raw file](https://github.com/puremourning/youcompleteme/blob/3976cafea5c037bcb16a4e3b7fd1def014b7de99/python/ycm/signature_help.py#L77)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

if we change ycmd to send byte offsets, then no change is needed here; the text properties expect byte offsets.
</blockquote></details>

Done.

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/4#-:-LqvBwzw7kAI_8XvhOad:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by puremourning** [comment]
Going to merge manually.

**Pull request closed without merging**
